version: 2.1

# orbs:
#   node: circleci/node@x.y

jobs:
  playwright-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-jammy
    # Steps to the job
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml xvfb-run npx playwright test --reporter=junit --project=chromium
      - store_test_results:
          path: /tmp/results.xml
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - playwright-tests

